-- ==============================================================================
-- DocMindX AI — Google Cloud BigQuery National Scale Telemetry Schema
-- Dataset: command_center
-- Optimized for high-throughput daily time-series telemetry across 30,000+ PHCs/CHCs
-- Partitioned by snapshot_date (DAY) and Clustered by state, district, facility_type
-- ==============================================================================

CREATE SCHEMA IF NOT EXISTS `command_center`
OPTIONS (
    location = 'asia-south1',
    description = 'National Public Health Resource & Supply Chain Telemetry Data Warehouse'
);

-- ------------------------------------------------------------------------------
-- 1. Facility Daily Operational Snapshot Table
-- Captures daily operational status, bed capacity, workforce presence, and inventory summary
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `command_center.facility_daily_snapshot` (
    snapshot_date DATE NOT NULL,
    facility_id STRING NOT NULL,
    facility_name STRING NOT NULL,
    facility_type STRING NOT NULL, -- DH, SDH, CHC, PHC
    state STRING NOT NULL,
    district STRING NOT NULL,
    pincode STRING,
    latitude FLOAT64,
    longitude FLOAT64,
    bed_capacity INT64,
    occupied_beds INT64,
    doctors_sanctioned INT64,
    doctors_present INT64,
    nurses_sanctioned INT64,
    nurses_present INT64,
    pharmacists_sanctioned INT64,
    pharmacists_present INT64,
    attendance_pct FLOAT64,
    attendance_status STRING, -- ADEQUATE, WARNING, CRITICAL
    critical_medicines_count INT64,
    warning_medicines_count INT64,
    total_daily_burn INT64,
    supply_health_score FLOAT64,
    provenance STRING NOT NULL, -- OBSERVED, DERIVED, SIMULATED
    synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
PARTITION BY snapshot_date
CLUSTER BY state, district, facility_type
OPTIONS (
    partition_expiration_days = 730, -- 2-year retention window for historical epidemiological audits
    description = 'Partitioned daily operational snapshot across Indian public health facilities'
);

-- ------------------------------------------------------------------------------
-- 2. AI Demand Forecast History Table
-- Records forward-looking 7-day to 30-day medicine consumption projections
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `command_center.demand_forecast_history` (
    forecast_date DATE NOT NULL,
    target_date DATE NOT NULL,
    facility_id STRING NOT NULL,
    facility_name STRING,
    state STRING NOT NULL,
    district STRING NOT NULL,
    medicine_id STRING NOT NULL,
    medicine_name STRING NOT NULL,
    baseline_burn_daily FLOAT64,
    forecasted_burn_daily FLOAT64,
    confidence_interval_lower FLOAT64,
    confidence_interval_upper FLOAT64,
    days_to_stockout FLOAT64,
    model_version STRING NOT NULL, -- e.g. ai_demand_forecaster_rf_v2
    wape_benchmark FLOAT64,        -- e.g. 0.0653 (6.53%)
    provenance STRING NOT NULL,     -- PROVENANCE_FORECAST
    synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
PARTITION BY forecast_date
CLUSTER BY state, district, medicine_id
OPTIONS (
    partition_expiration_days = 365,
    description = 'Historical repository of multi-day AI demand predictions generated by DocMindX models'
);

-- ------------------------------------------------------------------------------
-- 3. Inter-District Medicine Redistribution Audit Log
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `command_center.redistribution_manifest_log` (
    manifest_id STRING NOT NULL,
    generated_at TIMESTAMP NOT NULL,
    source_facility_id STRING NOT NULL,
    source_facility_name STRING NOT NULL,
    source_state STRING NOT NULL,
    source_district STRING NOT NULL,
    destination_facility_id STRING NOT NULL,
    destination_facility_name STRING NOT NULL,
    destination_state STRING NOT NULL,
    destination_district STRING NOT NULL,
    medicine_id STRING NOT NULL,
    medicine_name STRING NOT NULL,
    transfer_quantity INT64 NOT NULL,
    distance_km FLOAT64,
    estimated_transit_hours FLOAT64,
    status STRING NOT NULL, -- RECOMMENDED, CMO_VERIFIED, DISPATCHED, DELIVERED
    provenance STRING NOT NULL
)
PARTITION BY DATE(generated_at)
CLUSTER BY source_state, destination_state;
